-- create table if not exists education.example.book
-- (
--     id           bigint not null primary key,
--     price        numeric(38, 2),
--     publish_date date,
--     title        varchar(255)
-- );
--
-- create table if not exists education.example.author
-- (
--     id   bigint not null primary key,
--     name varchar(255),
--     age  numeric
-- );
--
-- alter table education.example.book
--     owner to postgres;